/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.lucas.view;

import br.com.lucas.dto.CheckAvailabilityRentais;
import br.com.lucas.dto.RentaisNew;
import br.com.lucas.model.Rentais;
import br.com.lucas.repository.CrasRepository;
import br.com.lucas.repository.RentaisRepository;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lucas
 */
public class Aluguel extends javax.swing.JFrame {

    /**
     * Creates new form Aluguel
     */
    public Aluguel() {
        initComponents();
        this.rentaisRepository = new RentaisRepository();
        var rentaisList = this.rentaisRepository.findAll();
        DefaultTableModel defaultTableModel = (DefaultTableModel) this.jTable1.getModel();
        for (Rentais rentais : rentaisList) {


            Object[] novaAlugel = new Object[]{
                    rentais.getId(),
                    rentais.getCras().getId(),
                    rentais.getCostumer().getId(),
                    rentais.getStart_date(),
                    rentais.getEnd_date(),
                    rentais.getTotal(),
                    rentais.getCreated_at()
            };
            defaultTableModel.addRow(novaAlugel);
        }
    }
 public Aluguel(String idCarro,String idMarca) {
        initComponents();
       this.jTextCarro.setText(idCarro);
       this.jTextCliente.setText(idMarca);
     this.rentaisRepository = new RentaisRepository();
     var rentaisList = this.rentaisRepository.findAll();
     DefaultTableModel defaultTableModel = (DefaultTableModel) this.jTable1.getModel();
     for (Rentais rentais : rentaisList) {


         Object[] novaAlugel = new Object[]{
                 rentais.getId(),
                 rentais.getCras().getId(),
                 rentais.getCostumer().getId(),
                 rentais.getStart_date(),
                 rentais.getEnd_date(),
                 rentais.getTotal(),
                 rentais.getCreated_at()
         };
         defaultTableModel.addRow(novaAlugel);
     }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextInicio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextDias = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabelTotal = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextCarro = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setText("Aluguel");

        jLabel2.setText("Id do carro");

        jLabel3.setText("Id do cliente");

        jLabel4.setText("Data de início");

        jTextInicio.setText("08/11/2022");

        jLabel5.setText("Número de dias de aluguel");

        jTextDias.setText("0");

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Carro", "Cliente", "Data de início", "Data de entrega", "Total R$", "Criado em"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("Calcular valor total");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabelTotal.setText("R$:0");

        jLabel7.setText("Valor total");

        jButton3.setText("Cancelar Aluguel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Voltar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Verificar disponibilidade");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jTextCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jTextDias, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jButton5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelTotal)
                                .addGap(125, 125, 125)
                                .addComponent(jButton2)
                                .addGap(36, 36, 36))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(26, 26, 26))))
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 888, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(16, 16, 16))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jTextCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTotal)
                            .addComponent(jLabel7)
                            .addComponent(jTextCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       if(this.jTextCarro.getText().equals("") || this.jTextDias.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Informe o id do carro.");
       }else{
            Integer id_carro = Integer.parseInt(this.jTextCarro.getText());         
            Long dias = Long.parseLong(this.jTextDias.getText());
            this.crasRepository = new CrasRepository();

           var consultTotal = this.crasRepository.consultTotalValue(id_carro,dias);

            this.jLabelTotal.setText("R$:"+consultTotal.getTotalValue());
       }
       
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(this.jTextCarro.getText().equals("") || this.jTextCliente.getText().equals("") || this.jTextInicio.getText().equals("") || this.jTextDias.getText().equals("")){
         JOptionPane.showMessageDialog(this, "Informe todos os campos.");
        }else{

        Integer id_carro = Integer.parseInt(this.jTextCarro.getText());
        Integer id_cliente = Integer.parseInt(this.jTextCliente.getText());
        String data = this.jTextInicio.getText();
        Long dias = Long.parseLong(this.jTextDias.getText());
        DefaultTableModel defaultTableModel = (DefaultTableModel) this.jTable1.getModel();
  try {
      this.rentaisRepository = new RentaisRepository();

      var rentaisNew = new RentaisNew(id_carro,id_cliente,data,dias);
      var rentais =this.rentaisRepository.post(rentaisNew);
      Object[] novaAlugel = new Object[]{
              rentais.getId(),
              id_carro,
              id_cliente,
              rentais.getStart_date(),
              rentais.getEnd_date(),
              rentais.getTotal(),
              rentais.getCreated_at()
      };

      defaultTableModel.addRow(novaAlugel);
      JOptionPane.showMessageDialog(this, "Salvo com sucesso.");
  }catch (Exception e){
      JOptionPane.showMessageDialog(this, "Erro.");
  }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int linhaSelecionada = this.jTable1.getSelectedRow();
     
     if(linhaSelecionada == -1){
          JOptionPane.showMessageDialog(this, "Por favor selecione uma linha.");
     }else{
         
         

         
         try {
             DefaultTableModel defaultTableModel = (DefaultTableModel) this.jTable1.getModel();
             this.rentaisRepository = new RentaisRepository();

             var id= defaultTableModel.getValueAt(linhaSelecionada,0).toString();

             
               var check = this.rentaisRepository.checkById(Integer.parseInt(id));
               System.out.println("c:"+check.isCheck());
               if(check.isCheck()){
              this.rentaisRepository.delete(Integer.parseInt(id));
      

             defaultTableModel.removeRow(linhaSelecionada);
             JOptionPane.showMessageDialog(this, "Aluguel Cancelado com sucesso.");
               }else{
             JOptionPane.showMessageDialog(this, "Data de locação iniciada.");
               }
             
         }catch (Exception e){
             JOptionPane.showMessageDialog(this, "Erro.");
         }

     }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      
         if(this.jTextCarro.getText().equals("") ||   this.jTextInicio.getText().equals("") || this.jTextDias.getText().equals("")){
         JOptionPane.showMessageDialog(this, "Informe todos os campos.");
         }else{
        Integer id_carro = Integer.parseInt(this.jTextCarro.getText());
        String data = this.jTextInicio.getText();
        Long dias = Long.parseLong(this.jTextDias.getText());
        var check = new CheckAvailabilityRentais(data,dias,id_carro);
        this.rentaisRepository = new RentaisRepository();
        try{
        this.rentaisRepository.checkAvailability(check);
          JOptionPane.showMessageDialog(this, "Data válida.");
        }catch(Exception e){
             JOptionPane.showMessageDialog(this, "Conflito de datas.");
        } 
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aluguel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aluguel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aluguel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aluguel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aluguel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextCarro;
    private javax.swing.JTextField jTextCliente;
    private javax.swing.JTextField jTextDias;
    private javax.swing.JTextField jTextInicio;
    // End of variables declaration//GEN-END:variables
    private RentaisRepository rentaisRepository;

    private CrasRepository crasRepository;
}
